In [1]:
import numpy as np

# Generate random integer matrix C of size 4x3
C = np.random.randint(1, 10, size=(4, 3))

# Compute A1 = C^T * C
A1 = np.dot(C.T, C)

# Print matrix C
print("Matrix C:")
print(C)

# Print matrix A1
print("\nMatrix A1:")
print(A1)

# Compute characteristic equation using numpy.linalg.eigvals
char_eq_coeff = np.poly(A1)
print("\nCharacteristic Equation Coefficients:")
print(char_eq_coeff)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A1)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Matrix C:
[[7 7 6]
 [8 3 5]
 [7 9 7]
 [1 1 6]]

Matrix A1:
[[163 137 137]
 [137 140 126]
 [137 126 146]]

Characteristic Equation Coefficients:
[ 1.00000e+00 -4.49000e+02  1.36440e+04 -1.05786e+05]

Eigenvalues:
[416.87984969  14.01815308  18.10199723]

Eigenvectors:
[[-0.60665629 -0.67577013 -0.41869186]
 [-0.5578917   0.73710903 -0.38134908]
 [-0.56632587 -0.0022369   0.82417838]]
