In [6]:
import numpy as np

# Generate random integer matrix C of size 4x3
C = np.random.randint(1, 10, size=(4, 3))

# Compute A1 = C^T * C
A1 = np.dot(C.T, C)

# Compute characteristic equation using numpy.linalg.eigvals
char_eq_coeff = np.poly(A1)

print("Characteristic Equation Coefficients:", char_eq_coeff)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A1)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Characteristic Equation Coefficients: [ 1.00000e+00 -5.50000e+02  3.60490e+04 -2.07711e+05]

Eigenvalues:
[475.03313679   6.37472169  68.59214153]

Eigenvectors:
[[ 0.71153042  0.68698343 -0.14757445]
 [ 0.4435361  -0.60201479 -0.66396831]
 [ 0.54497723 -0.40697906  0.73305379]]


In [9]:
import numpy as np

# Generate random integer matrix C of size 4x3
C = np.random.randint(1, 10, size=(4, 3))

# Compute A1 = C^T * C
A1 = np.dot(C.T, C)

# Print matrix C
print("Matrix C:")
print(C)

# Print matrix A1
print("\nMatrix A1:")
print(A1)

# Compute characteristic equation using numpy.linalg.eigvals
char_eq_coeff = np.poly(A1)
print("\nCharacteristic Equation Coefficients:")
print(char_eq_coeff)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A1)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Matrix C:
[[1 8 3]
 [3 1 5]
 [6 4 3]
 [2 6 9]]

Matrix A1:
[[ 50  47  54]
 [ 47 117  95]
 [ 54  95 124]]

Characteristic Equation Coefficients:
[ 1.00000e+00 -2.91000e+02  1.24080e+04 -1.41282e+05]

Eigenvalues:
[242.17286685  20.85982933  27.96730382]

Eigenvectors:
[[-0.34878474 -0.75258688  0.55853576]
 [-0.64616544 -0.23856359 -0.72495354]
 [-0.67883682  0.61375924  0.40308829]]
