In [3]:
import numpy as np

# Generate random integer matrix C of size 4x3
C = np.random.randint(1, 10, size=(4, 3))

# Compute A1 = C^T * C
A1 = np.dot(C.T, C)

# Print matrix C
print("Matrix C:")
print(C)

# Print matrix A1
print("\nMatrix A1:")
print(A1)

# Compute characteristic equation using numpy.linalg.eigvals
char_eq_coeff = np.poly(A1)
print("\nCharacteristic Equation Coefficients:")
print(char_eq_coeff)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A1)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Matrix C:
[[2 1 2]
 [9 9 5]
 [1 3 4]
 [9 5 7]]

Matrix A1:
[[167 131 116]
 [131 116  94]
 [116  94  94]]

Characteristic Equation Coefficients:
[ 1.0000e+00 -3.7700e+02  6.5210e+03 -2.8174e+04]

Eigenvalues:
[359.05707735   7.55002364  10.39289901]

Eigenvectors:
[[ 0.67347245  0.73476582 -0.08095715]
 [ 0.55278434 -0.57330603 -0.60477241]
 [ 0.49077932 -0.36254571  0.79227285]]
