In [14]:
import numpy as np

def power_method(A, max_iterations=1000):
    n = A.shape[0]
    
    # Initialize a random vector
    x = np.random.rand(n)
    x /= np.linalg.norm(x)  # Normalize the vector
    
    lambda_prev = 0
    
    # Print initial iterate
    print("Iterate 0: Eigenvalue estimate =", lambda_prev)
    
    # Iterate
    for i in range(1, max_iterations + 1):
        x_new = np.dot(A, x)
        lambda_ = np.dot(x_new, x)
        x_new /= np.linalg.norm(x_new)  # Normalize the vector
        
        # Print intermediate iterates
        if i <= 10:
            print(f"Iterate {i}: Eigenvalue estimate =", lambda_)
        
        lambda_prev = lambda_
        x = x_new
    
    return lambda_, x

# Example usage:
A1 = np.array([[99, 43, 95], [43, 132, 83], [95, 83, 109]])
print("\nMatrix A1:")
print(A1)
lambda_1, eigenvector_1 = power_method(A1)

# Normalize eigenvector
eigenvector_hat_1 = eigenvector_1 / np.linalg.norm(eigenvector_1)

print("\nEstimated largest eigenvalue (λ1):", lambda_1)
print("Corresponding eigenvector (x1):", eigenvector_1)
print("Normalized eigenvector (x_hat1):", eigenvector_hat_1)


Matrix A1:
[[ 99  43  95]
 [ 43 132  83]
 [ 95  83 109]]
Iterate 0: Eigenvalue estimate = 0
Iterate 1: Eigenvalue estimate = 185.8969064213737
Iterate 2: Eigenvalue estimate = 253.6052741728444
Iterate 3: Eigenvalue estimate = 261.5421893794115
Iterate 4: Eigenvalue estimate = 262.2465099158462
Iterate 5: Eigenvalue estimate = 262.30635608804437
Iterate 6: Eigenvalue estimate = 262.31142209829716
Iterate 7: Eigenvalue estimate = 262.3118508017625
Iterate 8: Eigenvalue estimate = 262.31188707916476
Iterate 9: Eigenvalue estimate = 262.3118901489951
Iterate 10: Eigenvalue estimate = 262.311890408767

Estimated largest eigenvalue (λ1): 262.3118904327814
Corresponding eigenvector (x1): [0.51931871 0.57438937 0.63275977]
Normalized eigenvector (x_hat1): [0.51931871 0.57438937 0.63275977]


In [16]:
import numpy as np

def power_method(A, epsilon=1e-6, max_iterations=1000):
    n = A.shape[0]
    x = np.random.rand(n)  # Initial guess for the eigenvector
    x = x / np.linalg.norm(x)  # Normalize the initial guess
    lambda_iterates = []
    
    for _ in range(max_iterations):
        x_new = np.dot(A, x)
        eigenvalue = np.dot(x_new, x)
        lambda_iterates.append(eigenvalue)
        x_new = x_new / np.linalg.norm(x_new)  # Normalize the new eigenvector
        
        # Check for convergence
        if np.linalg.norm(x_new - x) < epsilon:
            break
        
        x = x_new
    
    lambda1 = lambda_iterates[-1]
    x1 = x
    x1_normalized = x1 / np.linalg.norm(x1)
    
    return lambda1, x1_normalized, lambda_iterates

# Use A1 from question 1
lambda1_power, x1_power, lambda_iterates = power_method(A1)
print("\nMatrix A1:")
print(A1)

print("First 10 iterates of eigenvalue:")
print(lambda_iterates[:10])
print("\nFinal λ1 and ˆx1:")
print("λ1:", lambda1_power)
print("ˆx1:", x1_power)


Matrix A1:
[[ 99  43  95]
 [ 43 132  83]
 [ 95  83 109]]
First 10 iterates of eigenvalue:
[188.31329949095561, 255.32700732895, 261.69985563332585, 262.2599429805503, 262.3074934638987, 262.3115183488717, 262.3118589466151, 262.3118877683904, 262.311890207318, 262.3118904137025]

Final λ1 and ˆx1:
λ1: 262.31189043264476
ˆx1: [0.5193182  0.57439003 0.63275959]


In [17]:

import numpy as np

# Generate random integer matrix C of size 4x3
C = np.random.randint(1, 10, size=(4, 3))

# Compute A1 = C^T * C
#A1 = np.dot(C.T, C)

# Print matrix C
print("Matrix C:")
print(C)

# Print matrix A1
print("\nMatrix A1:")
print(A1)

# Compute characteristic equation using numpy.linalg.eigvals
char_eq_coeff = np.poly(A1)
print("\nCharacteristic Equation Coefficients:")
print(char_eq_coeff)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A1)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrix C:
[[8 7 2]
 [1 4 4]
 [8 1 9]
 [9 8 4]]

Matrix A1:
[[ 99  43  95]
 [ 43 132  83]
 [ 95  83 109]]

Characteristic Equation Coefficients:
[ 1.0000e+00 -3.4000e+02  2.0484e+04 -2.7670e+04]

Eigenvalues:
[262.31189043   1.38240137  76.3057082 ]

Eigenvectors:
[[-0.51931871 -0.60551017  0.60304685]
 [-0.57438937 -0.27517902 -0.77094316]
 [-0.63275977  0.74674891  0.204893  ]]
